function allconn = allconnset(n, parskI,parsc, useroptions)

if isempty(parskI)||isempty(parsc)
    parsk = repmat(struct,10);
    parsc = repmat(struct,10);
elseif length(parskI)==1
    warning('**Parsk** is only a 1x1 structure. Was layerdefs not called? This should not happen!')
    parsk = repmat(parskI(1),10);
elseif length(parsc)==1
    warning('**Parsc** is only a 1x1 structure. Was layerdefs not called? This should not happen!')
    parsk = repmat(parsc(1),10);
end
for i=1:length(parskI)
    parsk(i) = parskI(i);
end
%%% not needed for parsc because i didnt decide to call it something
%%% different. also, this structure is needlessly complated. it should be
%%% simplified if this starts to give strange results. 
% for i=1:length(parsc)
%     parsk(i) = parskI(i);
% end
allconn_set = {...
    {... %%%% ARCHITECTURE 1
    {'gwr1layer',   'gwr',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes'}...
    {'gwr2layer',   'gwr',{'vel'},                    'vel',[1 0],parsk(2),'knn',parsc(2),'nodes'}...
    {'gwr3layer',   'gwr',{'gwr1layer'},              'pos',[3 2],parsk(3),'knn',parsc(3),'nodes'}...
    {'gwr4layer',   'gwr',{'gwr2layer'},              'vel',[3 2],parsk(4),'knn',parsc(4),'nodes'}...
    {'gwrSTSlayer', 'gwr',{'gwr3layer','gwr4layer'},  'all',[3 2],parsk(5),'knn',parsc(5),'nodes'}...
    }...
    {...%%%% ARCHITECTURE 2
    {'gng1layer',   'gng',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes'}...
    {'gng2layer',   'gng',{'vel'},                    'vel',[1 0],parsk(2),'knn',parsc(2),'nodes'}...
    {'gng3layer',   'gng',{'gng1layer'},              'pos',[3 2],parsk(3),'knn',parsc(3),'nodes'}...
    {'gng4layer',   'gng',{'gng2layer'},              'vel',[3 2],parsk(4),'knn',parsc(4),'nodes'}...
    {'gngSTSlayer', 'gng',{'gng4layer','gng3layer'},  'all',[3 2],parsk(5),'knn',parsc(5),'nodes'}...
    }...
    {...%%%% ARCHITECTURE 3
    {'gng1layer',   'gng',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes'}...
    {'gng2layer',   'gng',{'vel'},                    'vel',[1 0],parsk(2),'knn',parsc(2),'nodes'}...
    {'gng3layer',   'gng',{'gng1layer'},              'pos',[3 0],parsk(3),'knn',parsc(3),'nodes'}...
    {'gng4layer',   'gng',{'gng2layer'},              'vel',[3 0],parsk(4),'knn',parsc(4),'nodes'}...
    {'gngSTSlayer', 'gng',{'gng4layer','gng3layer'},  'all',[3 0],parsk(5),'knn',parsc(5),'nodes'}...
    }...
    {...%%%% ARCHITECTURE 4
    {'gwr1layer',   'gwr',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes'}...
    {'gwr2layer',   'gwr',{'vel'},                    'vel',[1 0],parsk(2),'knn',parsc(2),'nodes'}...
    {'gwr3layer',   'gwr',{'gwr1layer'},              'pos',[3 0],parsk(3),'knn',parsc(3),'nodes'}...
    {'gwr4layer',   'gwr',{'gwr2layer'},              'vel',[3 0],parsk(4),'knn',parsc(4),'nodes'}...
    {'gwrSTSlayer', 'gwr',{'gwr3layer','gwr4layer'},  'all',[3 0],parsk(5),'knn',parsc(5),'nodes'}...
    }...
    {...%%%% ARCHITECTURE 5
    {'gwr1layer',   'gwr',{'pos'},                    'pos',[1 2 3],parsk(1),'knn',parsc(1),'nodes'}...
    {'gwr2layer',   'gwr',{'vel'},                    'vel',[1 2 3],parsk(2),'knn',parsc(2),'nodes'}...
    {'gwr3layer',   'gwr',{'gwr1layer'},              'pos',[3 2],parsk(3),'knn',parsc(3),'nodes'}...
    {'gwr4layer',   'gwr',{'gwr2layer'},              'vel',[3 2],parsk(4),'knn',parsc(4),'nodes'}...
    {'gwrSTSlayer', 'gwr',{'gwr3layer','gwr4layer'},  'all',[3 2],parsk(5),'knn',parsc(5),'nodes'}...
    }...
    {...%%%% ARCHITECTURE 6
    {'gwr1layer',   'gwr',{'pos'},                    'pos',[3 4 2],parsk(1),'knn',parsc(1),'nodes'}...
    {'gwr2layer',   'gwr',{'vel'},                    'vel',[3 4 2],parsk(2),'knn',parsc(2),'nodes'}...
    {'gwrSTSlayer', 'gwr',{'gwr1layer','gwr2layer'},  'all',[3 2],parsk(3),'knn',parsc(3),'nodes'}...
    }...
    {...%%%% ARCHITECTURE 7
    {'gwr1layer',   'gwr',{'all'},                    'all',[3 2], parsk(1),'knn',parsc(1),'nodes'}...
    {'gwr2layer',   'gwr',{'gwr1layer'},              'all',[3 2], parsk(2),'knn',parsc(2),'nodes'}...
    }...
    {...%%%% ARCHITECTURE 8
    {'gwr1layer',   'gwr',{'pos'},                    'pos',[9 0], parsk(1),'knn',parsc(1),'nodes'}... %% now there is a vector where q used to be, because we have the p overlap variable...
    }...
    {...%%%% ARCHITECTURE 9
    {'gwr1layer',   'gwr',{'pos'},                    'pos',3,parsk(1),'knn',parsc(1),'nodes'}...
    {'gwr2layer',   'gwr',{'vel'},                    'vel',3,parsk(2),'knn',parsc(2),'nodes'}...
    {'gwr3layer',   'gwr',{'gwr1layer'},              'pos',3,parsk(3),'knn',parsc(3),'nodes'}...
    {'gwr4layer',   'gwr',{'gwr2layer'},              'vel',3,parsk(4),'knn',parsc(4),'nodes'}...
    {'gwr5layer',   'gwr',{'gwr3layer'},              'pos',3,parsk(5),'knn',parsc(5),'nodes'}...
    {'gwr6layer',   'gwr',{'gwr4layer'},              'vel',3,parsk(6),'knn',parsc(6),'nodes'}...
    {'gwrSTSlayer', 'gwr',{'gwr6layer','gwr5layer'},  'all',3,parsk(7),'knn',parsc(7),'nodes'}
    }...
    {... %%%% ARCHITECTURE 10
    {'gwr1layer',   'gwr',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes'}...
    {'gwr2layer',   'gwr',{'vel'},                    'vel',[1 0],parsk(2),'knn',parsc(2),'nodes'}...
    {'gwrSTSlayer', 'gwr',{'gwr1layer','gwr2layer'},  'all',[3 2],parsk(3),'knn',parsc(3),'nodes'}...
    }...
    {... %%%% ARCHITECTURE 11
    {'gwr1layer',   'gwr',{'pos'},                    'pos',[3 2],parsk(1),'knn',parsc(1),'nodes'}...
    {'gwr2layer',   'gwr',{'vel'},                    'vel',[3 2],parsk(2),'knn',parsc(2),'nodes'}...
    {'gwr3layer',   'gwr',{'gwr1layer'},              'pos',[3 2],parsk(3),'knn',parsc(3),'nodes'}...
    {'gwr4layer',   'gwr',{'gwr2layer'},              'vel',[3 2],parsk(4),'knn',parsc(4),'nodes'}...
    {'gwrSTSlayer', 'gwr',{'gwr3layer','gwr4layer'},  'all',[1 0],parsk(5),'knn',parsc(5),'nodes'}...
    }...
    {... %%%% ARCHITECTURE 12
    {'gwr1layer',   'gwr',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes'}...
    {'gwr2layer',   'gwr',{'gwr1layer'},              'pos',[9 0],parsk(2),'knn',parsc(2),'nodes'}...
    }...
    {... %%%% ARCHITECTURE 13
    {'gwr1layer',   'gwr',{'vel'},                    'vel',[1 0],parsk(1),'knn',parsc(1),'nodes'}...
    {'gwr2layer',   'gwr',{'gwr1layer'},              'vel',[9 0],parsk(2),'knn',parsc(2),'nodes'}...
    }...
    {... %%%% ARCHITECTURE 14
    {'gwr1layer',   'gwr',{'vel'},                    'vel',[1 0],parsk(1),'knn',parsc(1),'nodes'}...
    }...
    {... %%%% ARCHITECTURE 15
    {'gwr1layer',   'gwr',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes'}...
    {'gwr2layer',   'gwr',{'vel'},                    'vel',[1 0],parsk(2),'knn',parsc(2),'nodes'}...
    {'gwr3layer',   'gwr',{'gwr1layer'},              'pos',[2 1],parsk(3),'knn',parsc(3),'nodes'}...
    {'gwr4layer',   'gwr',{'gwr2layer'},              'vel',[2 1],parsk(4),'knn',parsc(4),'nodes'}...
    {'gwrSTSlayer', 'gwr',{'gwr3layer','gwr4layer'},  'all',[4 3],parsk(5),'knn',parsc(5),'nodes'}...
    }...
    {... %%%% ARCHITECTURE 16
    {'gwr1layer',   'gwr',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes'}...
    }...
    {... %%%% ARCHITECTURE 17
    {'gwr1layer',   'gwr',{'all'},                    'all',[1 0],parsk(1),'knn',parsc(1),'nodes'}...
    }...
    {...%%%% ARCHITECTURE 18
    {'gwr1layer',   'gwr',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes'}...
    {'gwr2layer',   'gwr',{'vel'},                    'vel',[1 0],parsk(2),'knn',parsc(2),'nodes'}...
    {'gwrSTSlayer', 'gwr',{'gwr1layer','gwr2layer'},  'all',[100 0],parsk(3),'knn',parsc(3),'nodes'}...
    }...
    {...%%%% ARCHITECTURE 19
    {'gwr1layer',   'gwr',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),''}...
    {'knn2layer',   'knn',{'gwr1layer'},              'pos',[useroptions.w 0],parsk(2),'svm',parsc(2),'indexes'}...
    }...
    {...%%%% ARCHITECTURE 20
    {'knn1layer',   'knn',{'pos'},                    'pos',[1 110],parsk(1),'knn',parsc(1),'nodes'}...
    {'knn1layer',   'knn',{'pos'},                    'pos',[1 120],parsk(1),'knn',parsc(1),'nodes'}...
    {'knn1layer',   'knn',{'pos'},                    'pos',[1 130],parsk(1),'knn',parsc(1),'nodes'}...
    {'knn1layer',   'knn',{'pos'},                    'pos',[1 140],parsk(1),'knn',parsc(1),'nodes'}...
    {'knn1layer',   'knn',{'pos'},                    'pos',[1 150],parsk(1),'knn',parsc(1),'nodes'}...
    {'knn1layer',   'knn',{'pos'},                    'pos',[1 160],parsk(1),'knn',parsc(1),'nodes'}...
    {'knn1layer',   'knn',{'pos'},                    'pos',[1 170],parsk(1),'knn',parsc(1),'nodes'}...
    {'knn1layer',   'knn',{'pos'},                    'pos',[1 180],parsk(1),'knn',parsc(1),'nodes'}...
    {'knn1layer',   'knn',{'pos'},                    'pos',[1 190],parsk(1),'knn',parsc(1),'nodes'}...
    {'knn1layer',   'knn',{'pos'},                    'pos',[1 200],parsk(1),'knn',parsc(1),'nodes'}...
    }...
    {...%%%% ARCHITECTURE 21
    {'gwr1layer',   'knn',{'pos'},                    'pos',[7 0],parsk(1),'svm',parsc(1),'nodes'}...
    }...
    {...%%%% ARCHITECTURE 22
    {'gwr1layer',   'knn',{'pos'},                    'pos',[8 0],parsk(1),'svm',parsc(1),'nodes'}...
    }...
    {...%%%% ARCHITECTURE 23
    {'gwr1layer',   'knn',{'pos'},                    'pos',[9 0],parsk(1),'svm',parsc(1),'nodes'}...
    }...
    {...%%%% ARCHITECTURE 24
    {'gwr1layer',   'knn',{'pos'},                    'pos',[10 0],parsk(1),'svm',parsc(1),'nodes'}...
    }...
    {...%%%% ARCHITECTURE 25    
    {'knn1layer',   'knn',{'pos'},                    'pos',[1 0],parsk(1),'knn',parsc(1),'nodes'}...
    }...
    };
allconn = allconn_set{n};
end
